-- 1. PROFILES TABLOSU
CREATE TABLE public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  tc_no text unique,
  priority_level text check (priority_level in ('chronic', 'elderly', 'disabled', 'doctor', 'normal')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Profiles tablosu için RLS (Row Level Security) ayarları
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- 2. HOSPITALS TABLOSU
CREATE TABLE public.hospitals (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  latitude double precision,
  longitude double precision,
  capacity_total integer default 0,
  capacity_used integer default 0,
  queue_count integer default 0,
  status text check (status in ('Uygun', 'Orta Yoğun', 'Yoğun')),
  score integer default 100,
  phone text
);

-- Real-time özelliğini hastaneler tablosu için aktif ediyoruz
alter publication supabase_realtime add table public.hospitals;

-- 3. APPOINTMENTS TABLOSU
CREATE TABLE public.appointments (
  id bigint generated by default as identity primary key,
  hospital_id bigint references public.hospitals,
  patient_id uuid references public.profiles(id),
  doctor_name text,
  appointment_date timestamp with time zone,
  status text check (status in ('open', 'booked', 'cancelled')),
  priority_level integer default 0, -- daha yüksek rakam = daha yüksek öncelik
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Real-time özelliğini randevular tablosu için aktif ediyoruz
alter publication supabase_realtime add table public.appointments;

-- MOCK VERI EKLENMESI (Test İçin)
INSERT INTO public.hospitals (name, address, capacity_total, capacity_used, queue_count, status, score, phone) VALUES 
('Acıbadem Maslak Hastanesi - Acil', 'Maslak, Büyükdere Cd. No:40, Sarıyer', 25, 12, 5, 'Uygun', 95, '+90 212 304 4444'),
('American Hospital - Acil', 'Nişantaşı, Güzelbahçe Sk. No:20', 22, 9, 6, 'Uygun', 92, '+90 212 444 3777'),
('İstanbul Tıp Fakültesi - Acil', 'Fatih, Turgut Özal Millet Cd.', 40, 15, 8, 'Uygun', 82, '+90 212 414 2000'),
('Memorial Şişli Hastanesi - Acil', 'Şişli, Piyalepaşa Blv. No:5', 30, 8, 12, 'Orta Yoğun', 78, '+90 212 314 6666');
